[scheduler]
log_level = "info"
tick_interval_ms = 1000
max_concurrency = 10
shards = 0

[database]
host = "127.0.0.1"
port = 3306
username = "dagforge"
password = "dagforge"
database = "dagforge"
pool_size = 4

[api]
enabled = true
host = "127.0.0.1"
port = 8888
reuse_port = false

[dag_source]
directory = "./dags"
scan_interval_sec = 60
