id = "branching_example"
name = "Branching Example"
description = "Conditional execution based on data size"

[[tasks]]
id = "check_size"
name = "Check Data Size"
command = '''
SIZE=$((RANDOM % 100))
echo "Data size: $SIZE"
if [ $SIZE -gt 50 ]; then
  echo '["large_path"]'
else
  echo '["small_path"]'
fi
'''
is_branch = true

[[tasks.xcom_push]]
key = "branch"
source = "json"

[[tasks]]
id = "large_path"
name = "Process Large Dataset"
command = "echo \"Processing large dataset with batch mode\""
dependencies = ["check_size"]

[[tasks]]
id = "small_path"
name = "Process Small Dataset"
command = "echo \"Processing small dataset with simple mode\""
dependencies = ["check_size"]

[[tasks]]
id = "merge_results"
name = "Merge Results"
command = "echo \"Merging results from completed branch\""
dependencies = ["large_path", "small_path"]
trigger_rule = "one_success"
