id = "daily_etl"
name = "Daily ETL"
description = "Scheduled data pipeline with template variables"
cron = "0 2 * * *"
start_date = "2026-01-20"
catchup = false

[[tasks]]
id = "extract"
name = "Extract Data"
command = "echo \"Extracting data for {{ds}} (run {{run_id}})\""

[[tasks]]
id = "validate"
name = "Validate Data"
command = "echo \"Validating extracted data for {{ds_nodash}}\""
dependencies = ["extract"]

[[tasks]]
id = "transform"
name = "Transform Data"
command = "echo \"Transforming data for DAG {{dag_id}}, task {{task_id}}\""
dependencies = ["validate"]

[[tasks]]
id = "load"
name = "Load to Warehouse"
command = "echo \"Loading transformed data at {{execution_date}}\""
dependencies = ["transform"]

[[tasks]]
id = "notify"
name = "Send Notification"
command = "echo \"ETL complete for {{ds}}\""
dependencies = ["load"]
